version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - postgres
  php:
    build:
      context: .
      dockerfile: docker-files/php.dockerfile
    user: root
    volumes:
      - ./src:/var/www/html:delegated
  postgres:
    image: postgres:15
    env_file:
      - ./env/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  composer:
    build:
      context: ./docker-files
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    user: root
  artisan:
    build:
      context: .
      dockerfile: docker-files/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    user: root
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html

volumes:
  postgres_data: